name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}


  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: lint
    
    steps:
      - name: Build Docker Image
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: saveska/mindmappr-image:1.0
